import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const supabase = createServiceClient()

    // Get current offer with full details for reservation
    const { data: offer, error: fetchError } = await supabase
      .from('offer_quotes')
      .select(`
        id,
        status,
        lead_id,
        organization_id,
        customer_name,
        customer_email,
        customer_phone,
        guests,
        total_amount,
        currency,
        package_snapshot,
        travel_dates,
        price_breakdown
      `)
      .eq('id', id)
      .single()

    if (fetchError || !offer) {
      return NextResponse.json({ error: 'Ponuda nije pronađena' }, { status: 404 })
    }

    // Check if can be confirmed
    if (offer.status !== 'sent' && offer.status !== 'viewed') {
      return NextResponse.json({ error: 'Ponuda ne može biti potvrđena' }, { status: 400 })
    }

    // Update offer status to confirmed
    const { error: updateError } = await supabase
      .from('offer_quotes')
      .update({
        status: 'confirmed',
        confirmed_at: new Date().toISOString()
      })
      .eq('id', id)

    if (updateError) {
      console.error('Error confirming offer:', updateError)
      return NextResponse.json({ error: 'Greška pri potvrdi' }, { status: 500 })
    }

    // Create reservation with 72-hour hold
    const expiresAt = new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString()
    const depositAmount = offer.total_amount ? offer.total_amount * 0.3 : 0

    const { data: reservation, error: reservationError } = await supabase
      .from('reservations')
      .insert({
        organization_id: offer.organization_id,
        lead_id: offer.lead_id,
        // code is auto-generated by database trigger
        customer_name: offer.customer_name || 'Nepoznato',
        customer_phone: offer.customer_phone || '',
        customer_email: offer.customer_email,
        adults: offer.guests?.adults || 1,
        children: offer.guests?.children || 0,
        child_ages: offer.guests?.childAges || [],
        total_price: offer.total_amount || 0,
        deposit_amount: depositAmount,
        currency: offer.currency || 'EUR',
        status: 'pending',
        payment_option: 'deposit',
        expires_at: expiresAt,
        qualification_data: {
          offer_id: offer.id,
          package_name: offer.package_snapshot?.name,
          travel_dates: offer.travel_dates,
          price_breakdown: offer.price_breakdown,
        }
      })
      .select('id, code')
      .single()

    if (reservationError) {
      console.error('Error creating reservation:', reservationError)
      // Don't fail the whole request - offer is confirmed, just log the error
    }

    // Send confirmation email (fire and forget - don't block response)
    if (offer.customer_email && reservation) {
      try {
        const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://trak.rs'
        await fetch(`${baseUrl}/api/email/send-confirmation`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            organization_id: offer.organization_id,
            to: offer.customer_email,
            customer_name: offer.customer_name,
            reservation_code: reservation.code,
            package_name: offer.package_snapshot?.name || 'Paket',
            total_price: offer.total_amount,
            deposit_amount: depositAmount,
            currency: offer.currency || 'EUR',
            expires_at: expiresAt,
          })
        })
      } catch (emailError) {
        console.error('Error sending confirmation email:', emailError)
        // Don't fail - email is non-critical
      }
    }

    // Update lead stage to "Pregovori" or similar if lead exists
    // Also set awaiting_response = true so it shows in "Čeka odgovor" inbox
    if (offer.lead_id) {
      // Get pipeline stages
      const { data: stages } = await supabase
        .from('pipeline_stages')
        .select('id, name')
        .eq('organization_id', offer.organization_id)
        .eq('is_won', false)
        .eq('is_lost', false)
        .order('position', { ascending: true })

      // Find "Pregovori" stage or use 4th stage
      const pregovoriStage = stages?.find((s: { id: string; name: string }) =>
        s.name.toLowerCase().includes('pregovor') ||
        s.name.toLowerCase().includes('negotiat')
      ) || stages?.[3] || stages?.[2]

      // Update lead: move to pregovori stage AND set awaiting_response
      // This ensures the lead appears in "Čeka odgovor" requiring agent attention
      await supabase
        .from('leads')
        .update({
          stage_id: pregovoriStage?.id,
          awaiting_response: true,
          updated_at: new Date().toISOString()
        })
        .eq('id', offer.lead_id)
    }

    return NextResponse.json({
      success: true,
      reservation_code: reservation?.code
    })
  } catch (error) {
    console.error('Error confirming offer:', error)
    return NextResponse.json({ error: 'Greška servera' }, { status: 500 })
  }
}
